version: '3.4'
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  web:
    image: express-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      MONGODB_USER: elevators
      MONGODB_PASSWORD: elevators
      MONGODB_URL: cluster0.2lln1gg.mongodb.net
    ports:
      - "3000:3000"